// src/components/apps/vscode/VscodeApp.tsx
import { useMemo } from 'react'
import FileNavigation from './components/FileNavigation'
import TextEditor from './components/TextEditor'
import vscodeData from './data/vscodeData.json'
import filesIcon from './images/vscode-files.png'
import searchIcon from './images/vscode-search.png'
import gitIcon from './images/vscode-git.png'
import debugIcon from './images/vscode-debug.png'
import extIcon from './images/vscode-ext.png'
import './VscodeApp.scss'

type VscodeData = Record<string, unknown>

export default function VscodeApp() {
  const { files, folders } = useMemo(() => {
    const files: string[] = []
    const folders: string[] = []
    for (const item in vscodeData) {
      if (item.includes('.')) files.push(item)
      else folders.push(item)
    }
    return { files, folders }
  }, [])

  return (
    <div className="vscode-window">
      <div className="sidebar">
        <button>
          <img src={filesIcon} alt="files" />
        </button>
        <button>
          <img src={searchIcon} alt="search" />
        </button>
        <button>
          <img src={gitIcon} alt="git" />
        </button>
        <button>
          <img src={debugIcon} alt="debug" />
        </button>
        <button>
          <img src={extIcon} alt="extensions" />
        </button>
      </div>
      <FileNavigation
        files={files}
        folders={folders}
        vscodeData={vscodeData as VscodeData}
      />
      <TextEditor files={files} />
    </div>
  )
}

// src/components/apps/vscode/VscodeApp.vue
<script>
import FileNavigation from './components/FileNavigation'
import TextEditor from './components/TextEditor'
import vscodeData from './data/vscodeData.json'

export default {
  name: 'VscodeApp',
  components: {
    FileNavigation,
    TextEditor
  },
  data() {
    return {
      files: [],
      folders: [],
      vscodeData
    }
  },
  beforeMount() {
    this.parseVscodeData();
  },
  methods: {
    parseVscodeData() {
      for (let item in vscodeData) {
        if (item.includes('.')) {
          this.files.push(item);
        } else {
          this.folders.push(item);
        }
      }
    }
  }
}
</script>

<template>
  <div class="vscode-window">
    <div class="sidebar">
      <button><img src="./images/vscode-files.png"></button>
      <button><img src="./images/vscode-search.png"></button>
      <button><img src="./images/vscode-git.png"></button>
      <button><img src="./images/vscode-debug.png"></button>
      <button><img src="./images/vscode-ext.png"></button>
    </div>
    <FileNavigation :files="files" :folders="folders" />
    <TextEditor :files="files" />
  </div>
</template>

<style lang="scss" scoped>
@import "../../../assets/scss/variables-mac";

.vscode-window {
  width: 100%;
  height: 100%;
  background-color: $vscode-light;
  display: flex;
}

.sidebar {
  display: flex;
  flex-direction: column;

  button {
    background-color: transparent;
    border: none;
    width: 45px;
    height: 45px;
    padding: 0;
    margin: 5px 0;

    img {
      width: 100%;
    }
  }
}
</style>
