// src/components/apps/terminal/TerminalApp.tsx
import { useMemo, useRef } from 'react'
import Terminal from 'react-console-emulator'
import { cmdData, config, subcmdData } from './utils/constants'
import './TerminalApp.scss'

export default function TerminalApp() {
  // Mutable shell state, mirroring the original jQuery.terminal closure:
  // `cd` mutates the working directory + listing, and `ls`/`pwd` read them.
  const shell = useRef({
    type: 'desktop',
    ls: cmdData.ls,
    pwd: cmdData.pwd,
  })

  const commands = useMemo(
    () => ({
      help: { fn: () => cmdData.help },
      ls: { fn: () => shell.current.ls },
      pwd: { fn: () => shell.current.pwd },
      sudo: { fn: () => cmdData.sudo },
      cd: {
        fn: (...args: string[]) => {
          const subcmd = args[0]?.toLowerCase()
          if (!subcmd) return ''
          const target = subcmdData[subcmd]
          if (!target) return `cd: no such file or directory: ${subcmd}`

          shell.current.ls = target.files
          shell.current.pwd = `~/Brenda_Zhang/Desktop${target.folder}`
          const denied =
            subcmd === '../' && shell.current.type === 'desktop'
          shell.current.type = target.type
          return denied ? 'zsh: cd: permission denied' : ''
        },
      },
    }),
    []
  )

  const greeting = useMemo(() => `Last login: ${new Date()}`, [])

  return (
    <Terminal
      className="terminal"
      commands={commands}
      welcomeMessage={greeting}
      promptLabel={config.prompt}
      errorText="zsh: command not found: [command]"
      ignoreCommandCase
      noDefaults
    />
  )
}

// src/components/apps/terminal/TerminalApp.vue
<script>
import $ from 'jquery'
import 'jquery.terminal'
import {cmdData, config, subcmdData} from './utils/constants.js'

export default {
  name: 'TerminalApp',
  mounted() {
    let type = 'desktop';

    $('.terminal').terminal(function(command) {
      let args = command.toLowerCase().split(' ');
      let cmd = args[0];
      let subcmd = args[1] && args[1].toLowerCase();

      if (!cmd) {
        this.echo('');
      } else if (cmd === 'cd') {
        if (!subcmd) {
          this.echo('');
        } else if (Object.keys(subcmdData).includes(subcmd)) {
          cmdData.ls = subcmdData[subcmd].files;
          cmdData.pwd = `~/Brenda_Zhang/Desktop${subcmdData[subcmd].folder}\n`;
          if (subcmd === '../' && type === 'desktop') {
            this.echo('zsh: cd: permission denied\n');
          }
          type = subcmdData[subcmd].type;
        } else {
          this.echo('cd: no such file or directory: ' + subcmd);
        }
      } else if (Object.keys(cmdData).includes(cmd)) {
        this.echo(cmdData[cmd]);
      } else {
        this.echo('zsh: command not found: ' + command);
      }
    }, config);
  }
}
</script>

<template>
  <div class="terminal" />
</template>

<style lang="scss" scoped>
  .terminal {
    height: 100%;
  }
</style>
