// src/components/desktops/mac/components/DesktopFolder.tsx
import directoryIcon from '../images/directory.png'
import './DesktopFolder.scss'

interface Props {
  title: string
  onClick: () => void
}

export default function DesktopFolder({ title, onClick }: Props) {
  return (
    <div className="desktop-icon-container" onClick={onClick}>
      <img className="desktop-icon" src={directoryIcon} alt={title} />
      <p>{title}</p>
    </div>
  )
}

// src/components/desktops/mac/components/DesktopFolder.vue
<template>
  <div class="desktop-icon-container">
    <img class="desktop-icon" src="../images/directory.png" /><p>{{title}}</p>
  </div>
</template>

<script>
export default {
  name: 'DesktopFolder',
  props: ['title']
}
</script>

<style lang="scss" scoped>
@import "../../../../assets/scss/mixins";

.desktop-icon-container {
  @include short-transition;
  width: 95px;
  height: auto;
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  padding: 10px 0;
  margin-bottom: 10px;
  border-radius: 5px;

  &:hover {
    background-color: rgba(0, 0, 0, 0.55);
  }

  p {
    color: #fff;
    margin-top: 5px;
  }
}

.desktop-icon {
  width: 60px;
}
</style>
