// src/components/apps/finder/FinderApp.vue
<script>
import FinderItem from './components/FinderItem'
import ItemDescription from './components/ItemDescription'
import finderData from './data/finderData.json'

export default {
  name: 'FinderApp',
  components: {
    FinderItem,
    ItemDescription
  },
  props: {
    currentFolder: {
      type: String,
      default: ''
    },
    openedFromDesktop: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      currentItem: {},
      expanded: false,
      finderData: finderData
    }
  },
  methods: {
    selectFinderItem(type, finderItem) {
      if (type === 'folder') {
        this.currentItem = {}
        this.expanded = false
        this.$emit('item-click', finderItem)
      } else if (type === 'item') {
        this.openedFromDesktop = false
        this.currentItem = finderItem
        this.expanded = false
      }
    }
  }
}
</script>

<template>
  <div class="finder-file-container">
    <div class="finder-section">
      <FinderItem
        v-for="(folder, key) in finderData.folders"
        :key="key"
        :current-folder="currentFolder"
        :finder-item="folder"
        type="folder"
        @item-click="selectFinderItem"
      />
    </div>
    <div class="finder-section">
      <FinderItem
        v-for="(item, key) in finderData.items[currentFolder.toLowerCase()]"
        :key="key"
        :current-item="currentItem"
        :finder-item="item"
        type="item"
        @item-click="selectFinderItem"
      />
    </div>
    <div class="finder-section">
      <ItemDescription
        :expanded="expanded"
        :item="openedFromDesktop ? {} : currentItem"
        @show-click="expanded = !expanded"
      />
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import '../../../assets/scss/variables-mac';

.finder-file-container {
  height: 95.25%;
  width: 100%;
  color: $finder-text-font-color;
  display: flex;
  flex-direction: row;
}

.finder-section {
  height: 100%;
  width: 33%;
  border-right: 1px solid $mac-titlebar-color-border;
  padding: 2px 0;
  overflow-x: hidden;
  overflow-y: auto;
}

.finder-section:last-child {
  width: 34%;
  border-right: none;
}

@media screen and (max-width: 650px) {
  .finder-section {
    width: 50%;
  }

  .finder-section:last-child {
    display: none;
  }

  .finder-selected-item {
    display: none;
  }
}
</style>

// src/components/apps/finder/FinderApp.tsx
import { useState } from 'react'
import FinderItem from './components/FinderItem'
import ItemDescription from './components/ItemDescription'
import rawFinderData from './data/finderData.json'
import { FinderData, FinderFile, FinderFolder } from '../../../types'
import './FinderApp.scss'

const finderData = rawFinderData as unknown as FinderData

interface Props {
  currentFolder: string
  openedFromDesktop: boolean
  onFolderChange: (name: string) => void
  onItemOpen: () => void
}

export default function FinderApp({
  currentFolder,
  openedFromDesktop,
  onFolderChange,
  onItemOpen,
}: Props) {
  const [currentItem, setCurrentItem] = useState<FinderFile | null>(null)
  const [expanded, setExpanded] = useState(false)

  const selectFolder = (folder: FinderFolder) => {
    setCurrentItem(null)
    setExpanded(false)
    onFolderChange(folder.name)
  }

  const selectItem = (item: FinderFile) => {
    onItemOpen()
    setCurrentItem(item)
    setExpanded(false)
  }

  const items = finderData.items[currentFolder.toLowerCase()] ?? {}

  return (
    <div className="finder-file-container">
      <div className="finder-section">
        {Object.entries(finderData.folders).map(([key, folder]) => (
          <FinderItem
            key={key}
            currentFolder={currentFolder}
            finderItem={folder}
            type="folder"
            onItemClick={() => selectFolder(folder)}
          />
        ))}
      </div>
      <div className="finder-section">
        {Object.entries(items).map(([key, item]) => (
          <FinderItem
            key={key}
            currentItem={currentItem}
            finderItem={item}
            type="item"
            onItemClick={() => selectItem(item)}
          />
        ))}
      </div>
      <div className="finder-section">
        <ItemDescription
          expanded={expanded}
          item={openedFromDesktop ? {} : (currentItem ?? {})}
          onShowClick={() => setExpanded((e) => !e)}
        />
      </div>
    </div>
  )
}
