// src/components/apps/vscode/components/FileItem.tsx
import { toImageMap } from '../../../../utils/images'
import './FileItem.scss'

const icons = toImageMap(
  import.meta.glob('../images/icon-*.svg', { eager: true, import: 'default' })
)

interface Props {
  itemName: string
  itemType?: 'file' | 'tab'
}

export default function FileItem({ itemName, itemType = 'file' }: Props) {
  const ext = itemName.split('.')[1]

  return (
    <div className={itemType}>
      <img className="icon" src={icons[`icon-${ext}.svg`]} alt="" />
      <p>{itemName}</p>
    </div>
  )
}

// src/components/apps/vscode/components/FileItem.vue
<script>
export default {
  name: 'FileItem',
  props: {
    itemName: {
      type: String,
      default: ''
    },
    itemType: {
      type: String,
      default: 'file'
    }
  }
}
</script>

<template>
  <div :class="itemType">
    <img
      class="icon"
      :src="require(`../images/icon-${itemName.split('.')[1]}.svg`)"
    />
    <p>{{ itemName }}</p>
  </div>
</template>

<style lang="scss" scoped>
@import '../scss/shared.scss';

.tab {
  min-width: 150px;
  height: 100%;
  background-color: $vscode-highlight;
  border-right: 1px solid $vscode-dark;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;

  p {
    cursor: pointer;
    font-size: 13px;
  }
}
</style>
