// src/components/apps/vscode/components/FolderItem.vue
<script>
export default {
  name: 'FolderItem',
  props: {
    files: {
      type: Object,
      default: () => {}
    },
    itemName: {
      type: String,
      default: ''
    },
    itemType: {
      type: String,
      default: 'file'
    }
  }
}
</script>

<template>
  <div :class="itemType">
    <img class="icon" :src="require('../images/icon-folder.svg')">
    <p>{{ itemName }}</p>
  </div>
</template>

<style lang="scss" scoped>
@import '../scss/shared.scss';
</style>

// src/components/apps/vscode/components/FolderItem.tsx
import folderIcon from '../images/icon-folder.svg'
import './FolderItem.scss'

interface Props {
  files: unknown
  itemName: string
  itemType?: 'file' | 'tab'
}

export default function FolderItem({ itemName, itemType = 'file' }: Props) {
  return (
    <div className={itemType}>
      <img className="icon" src={folderIcon} alt="" />
      <p>{itemName}</p>
    </div>
  )
}
